// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds_query.sql

package autodatabase

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, user_id, title, description, url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, url, last_fetched_at, created_at, updated_at, last_publisher_published_at
`

type CreateFeedParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description string
	Url         string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Url,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublisherPublishedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = $1
    AND user_id = $2
`

type DeleteFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	return err
}

const getAllFeeds = `-- name: GetAllFeeds :many
SELECT id, user_id, title, description, url, last_fetched_at, created_at, updated_at, last_publisher_published_at
FROM feeds
LIMIT $1 OFFSET $2
`

type GetAllFeedsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllFeeds(ctx context.Context, arg GetAllFeedsParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPublisherPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeedsByUserID = `-- name: GetAllFeedsByUserID :many
SELECT id, user_id, title, description, url, last_fetched_at, created_at, updated_at, last_publisher_published_at
FROM feeds
WHERE user_id = $1
LIMIT $2 OFFSET $3
`

type GetAllFeedsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllFeedsByUserID(ctx context.Context, arg GetAllFeedsByUserIDParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPublisherPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, user_id, title, description, url, last_fetched_at, created_at, updated_at, last_publisher_published_at
FROM feeds
WHERE id = $1
`

func (q *Queries) GetFeedByID(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublisherPublishedAt,
	)
	return i, err
}

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :many
SELECT id,
    url,
    last_publisher_published_at
FROM feeds
WHERE last_fetched_at < $1
    OR last_fetched_at IS NULL
ORDER BY last_fetched_at ASC NULLS FIRST
LIMIT $2
`

type GetNextFeedToFetchParams struct {
	LastFetchedAt sql.NullTime
	Limit         int32
}

type GetNextFeedToFetchRow struct {
	ID                       uuid.UUID
	Url                      string
	LastPublisherPublishedAt sql.NullTime
}

func (q *Queries) GetNextFeedToFetch(ctx context.Context, arg GetNextFeedToFetchParams) ([]GetNextFeedToFetchRow, error) {
	rows, err := q.db.QueryContext(ctx, getNextFeedToFetch, arg.LastFetchedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNextFeedToFetchRow
	for rows.Next() {
		var i GetNextFeedToFetchRow
		if err := rows.Scan(&i.ID, &i.Url, &i.LastPublisherPublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET title = $1,
    description = $2,
    url = $3,
    updated_at = timezone('utc', now())
WHERE user_id = $4
RETURNING id, user_id, title, description, url, last_fetched_at, created_at, updated_at, last_publisher_published_at
`

type UpdateFeedParams struct {
	Title       string
	Description string
	Url         string
	UserID      uuid.UUID
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublisherPublishedAt,
	)
	return i, err
}

const updateLastFetchedAt = `-- name: UpdateLastFetchedAt :exec
UPDATE feeds
SET last_fetched_at = timezone('utc', now()),
    updated_at = timezone('utc', now())
WHERE id = $1
`

func (q *Queries) UpdateLastFetchedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastFetchedAt, id)
	return err
}

const updateLastPublisherPublishedAt = `-- name: UpdateLastPublisherPublishedAt :exec
UPDATE feeds
SET last_publisher_published_at = $1,
    updated_at = timezone('utc', now())
WHERE id = $2
`

type UpdateLastPublisherPublishedAtParams struct {
	LastPublisherPublishedAt sql.NullTime
	ID                       uuid.UUID
}

func (q *Queries) UpdateLastPublisherPublishedAt(ctx context.Context, arg UpdateLastPublisherPublishedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastPublisherPublishedAt, arg.LastPublisherPublishedAt, arg.ID)
	return err
}
