// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_follow_query.sql

package autodatabase

import (
	"context"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :exec
INSERT INTO feed_follow (user_id, feed_id)
VALUES ($1, $2)
RETURNING user_id, feed_id, created_at
`

type CreateFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, createFeedFollow, arg.UserID, arg.FeedID)
	return err
}

const deleteFeedFollow = `-- name: DeleteFeedFollow :exec
DELETE FROM feed_follow
WHERE feed_id = $1
    AND user_id = $2
`

type DeleteFeedFollowParams struct {
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollow, arg.FeedID, arg.UserID)
	return err
}

const getFeedFollowerCount = `-- name: GetFeedFollowerCount :one
SELECT COUNT(user_id)
FROM feed_follow
WHERE feed_id = $1
`

func (q *Queries) GetFeedFollowerCount(ctx context.Context, feedID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedFollowerCount, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFeedFollowers = `-- name: GetFeedFollowers :many
SELECT user_id, feed_id, created_at
FROM feed_follow
WHERE feed_id = $1
`

func (q *Queries) GetFeedFollowers(ctx context.Context, feedID uuid.UUID) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowers, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(&i.UserID, &i.FeedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowedFeeds = `-- name: GetFollowedFeeds :many
SELECT user_id, feed_id, created_at
FROM feed_follow
WHERE user_id = $1
LIMIT $2 OFFSET $3
`

type GetFollowedFeedsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetFollowedFeeds(ctx context.Context, arg GetFollowedFeedsParams) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedFeeds, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(&i.UserID, &i.FeedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
