// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package autodatabase

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID                       uuid.UUID
	UserID                   uuid.UUID
	Title                    string
	Description              string
	Url                      string
	LastFetchedAt            sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                time.Time
	LastPublisherPublishedAt sql.NullTime
}

type FeedFollow struct {
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
}

type Post struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
