// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts_query.sql

package autodatabase

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
        id,
        feed_id,
        title,
        description,
        url,
        published_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePostParams struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.FeedID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.PublishedAt,
	)
	return err
}

const getPostsByUser = `-- name: GetPostsByUser :many
SELECT id, posts.feed_id, title, description, url, published_at, posts.created_at, updated_at, user_id, feed_follow.feed_id, feed_follow.created_at
FROM posts
    LEFT JOIN feed_follow ON posts.feed_id = feed_follow.feed_id
WHERE feed_follow.user_id = $1
ORDER BY posts.published_at DESC
LIMIT $2 OFFSET $3
`

type GetPostsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetPostsByUserRow struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.NullUUID
	FeedID_2    uuid.NullUUID
	CreatedAt_2 sql.NullTime
}

func (q *Queries) GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]GetPostsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByUserRow
	for rows.Next() {
		var i GetPostsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID_2,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
