package resources

import (
	"time"

	"github.com/google/uuid"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
)

type FeedResource struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Url         string    `json:"url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func ToFeedResource(feed db.Feed) FeedResource {
	return FeedResource{
		ID:          feed.ID,
		UserID:      feed.UserID,
		Title:       feed.Title,
		Description: feed.Description,
		Url:         feed.Url,
		UpdatedAt:   feed.UpdatedAt,
	}
}

func ToFeedResourceCollection(feeds []db.Feed) []FeedResource {
	newFeeds := make([]FeedResource, len(feeds))
	for i, feed := range feeds {
		newFeeds[i] = ToFeedResource(feed)
	}
	return newFeeds
}
