package resources

import (
	"time"

	"github.com/google/uuid"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
)

type PostResource struct {
	ID          uuid.UUID `json:"id"`
	FeedID      uuid.UUID `json:"feed_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Url         string    `json:"url"`
	PublishedAt time.Time `json:"published_at"`
}

func ToPostResource(post db.GetPostsByUserRow) PostResource {
	return PostResource{
		ID:          post.ID,
		FeedID:      post.FeedID,
		Title:       post.Title,
		Description: post.Description.String,
		Url:         post.Url,
		PublishedAt: post.PublishedAt.Time,
	}
}

func ToPostResourceCollection(posts []db.GetPostsByUserRow) []PostResource {
	newPosts := make([]PostResource, len(posts))
	for i, post := range posts {
		newPosts[i] = ToPostResource(post)
	}
	return newPosts
}
