package services

import (
	"context"
	"database/sql"
	"encoding/xml"
	"io"
	"log"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
	"github.com/naywin-programmer/RSS_Aggregator/utils"
)

type (
	rssFeed struct {
		Channel struct {
			Title       string    `xml:"title"`
			Description string    `xml:"description"`
			PubDate     string    `xml:"lastBuildDate"`
			Image       rssImage  `xml:"image"`
			Link        string    `xml:"link"`
			Items       []rssItem `xml:"item"`
		} `xml:"channel"`
	}

	rssImage struct {
		URL string `xml:"url"`
	}

	rssItem struct {
		Title       string `xml:"title"`
		Description string `xml:"description"`
		PubDate     string `xml:"pubDate"`
		Link        string `xml:"link"`
	}
)

func (rf *rssFeed) FetchURL(url string) error {
	httpClient := http.Client{
		Timeout: 10 * time.Second,
	}

	resp, err := httpClient.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	err = xml.Unmarshal(data, rf)
	if err != nil {
		return err
	}

	return nil
}

func RssScraperRun(database *db.Queries, concurrent int, requestInterval time.Duration, fetchInterval time.Time) {
	log.Printf("Scraping Start: %v goroutines running in every %s", concurrent, requestInterval)
	setIntervalTicker := time.NewTicker(requestInterval)

	// Do While Loop
	for ; ; <-setIntervalTicker.C {
		nextFetchAt := sql.NullTime{
			Time:  fetchInterval,
			Valid: true,
		}

		feeds, err := database.GetNextFeedToFetch(context.Background(), db.GetNextFeedToFetchParams{
			LastFetchedAt: nextFetchAt,
			Limit:         int32(concurrent),
		})
		if err != nil {
			log.Printf("next feeds query error : %v", feeds)
			continue
		}
		log.Println("Feeds To Fetch:", len(feeds))

		wg := &sync.WaitGroup{}
		for _, feed := range feeds {
			wg.Add(1)

			go func() {
				defer wg.Done()

				err := database.UpdateLastFetchedAt(context.Background(), feed.ID)
				if err != nil {
					log.Printf("error while updating feeds last fetched at: %v", err)
					return
				}

				rf := rssFeed{}
				err = rf.FetchURL(feed.Url)
				if err != nil {
					log.Printf("feeds fetching error url : %v, error: %v", feed.Url, err)
					return
				}

				lastPublisherPublishedAt := sql.NullTime{}
				lastPublisherPublishedAtDate, err := time.Parse(utils.RFC1123ZDateFormatVariant(), rf.Channel.PubDate)
				if err == nil {
					lastPublisherPublishedAt.Time = lastPublisherPublishedAtDate.UTC()
					lastPublisherPublishedAt.Valid = true
				}

				if lastPublisherPublishedAtDate == feed.LastPublisherPublishedAt.Time {
					return
				}

				for _, item := range rf.Channel.Items {
					description := sql.NullString{}
					if item.Description != "" {
						description.String = item.Description
						description.Valid = true
					}

					publishedAt := sql.NullTime{}
					pubDate, err := time.Parse(utils.RFC1123ZDateFormatVariant(), item.PubDate)
					if err == nil {
						publishedAt.Time = pubDate.UTC()
						publishedAt.Valid = true
					}

					link, err := utils.ExtractUrl(item.Link)
					if err != nil {
						log.Printf("feed item url parsing error: %v", err)
						continue
					}

					err = database.CreatePost(context.Background(), db.CreatePostParams{
						ID:          uuid.New(),
						FeedID:      feed.ID,
						Title:       item.Title,
						Description: description,
						Url:         link,
						PublishedAt: publishedAt,
					})
					if err != nil {
						if strings.Contains(err.Error(), "duplicate") {
							continue
						}
						log.Printf("fail to create post: %v", err)
					}
				}

				err = database.UpdateLastPublisherPublishedAt(context.Background(), db.UpdateLastPublisherPublishedAtParams{
					LastPublisherPublishedAt: lastPublisherPublishedAt,
					ID:                       feed.ID,
				})
				if err != nil {
					log.Printf("error while updating feeds last publisher published at: %v", err)
					return
				}
			}()
		}
		wg.Wait()
	}
}
