package controllersapi

import (
	"fmt"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
	cf "github.com/naywin-programmer/RSS_Aggregator/configs"
	mi "github.com/naywin-programmer/RSS_Aggregator/middlewares"
	rs "github.com/naywin-programmer/RSS_Aggregator/resources"
	ut "github.com/naywin-programmer/RSS_Aggregator/utils"
)

type feedController struct {
}

var FeedController = feedController{}

func (c feedController) Index(w http.ResponseWriter, r *http.Request) {
	var limit int = 10

	page, err := strconv.Atoi(r.URL.Query().Get("page"))
	if err != nil {
		page = 1
	}

	offset := (page - 1) * limit
	if offset < 0 {
		offset = 0
	}

	feeds, err := cf.DBConnection.DB.GetAllFeeds(r.Context(), db.GetAllFeedsParams{
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Error while loading feeds: %v", err))
		return
	}

	ut.RespondWithJSON(w, http.StatusOK, rs.ToFeedResourceCollection(feeds))
}

func (c feedController) Store(w http.ResponseWriter, r *http.Request) {
	charCount := 200

	type parameters struct {
		Title       string `json:"title"`
		Description string `json:"description"`
		Url         string `json:"url"`
	}

	params, err := ut.DecodeJsonParams(w, r, &parameters{})
	if err != nil {
		return
	}

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	url, err := ut.ExtractUrl(params.Url)
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, err.Error())
		return
	}

	if len(url) > charCount {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("url length can't have more than %v characters.", charCount))
		return
	}

	feed, err := cf.DBConnection.DB.CreateFeed(r.Context(), db.CreateFeedParams{
		ID:          uuid.New(),
		UserID:      authUser.ID,
		Title:       params.Title,
		Description: params.Description,
		Url:         url,
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Couldn't create new feed: %v", err))
		return
	}

	// Follow the feed instantly after creating
	_ = cf.DBConnection.DB.CreateFeedFollow(r.Context(), db.CreateFeedFollowParams{
		UserID: authUser.ID,
		FeedID: feed.ID,
	})

	ut.RespondWithJSON(w, http.StatusCreated, rs.ToFeedResource(feed))
}

func (c feedController) Show(w http.ResponseWriter, r *http.Request) {
	requestedUUID, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	feed, err := cf.DBConnection.DB.GetFeedByID(r.Context(), requestedUUID)
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	ut.RespondWithJSON(w, http.StatusOK, rs.ToFeedResource(feed))
}

func (c feedController) Update(w http.ResponseWriter, r *http.Request) {

}

func (c feedController) Delete(w http.ResponseWriter, r *http.Request) {
	feedId, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	err = cf.DBConnection.DB.DeleteFeed(r.Context(), db.DeleteFeedParams{
		ID:     feedId,
		UserID: authUser.ID,
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Can not delete feed: %v", err))
		return
	}

	ut.RespondSuccessWithJSON(w, http.StatusCreated, "Feed deleted successfully.")
}
