package controllersapi

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
	cf "github.com/naywin-programmer/RSS_Aggregator/configs"
	mi "github.com/naywin-programmer/RSS_Aggregator/middlewares"
	ut "github.com/naywin-programmer/RSS_Aggregator/utils"
)

type feedFollowController struct {
}

var FeedFollowController = feedFollowController{}

func (c feedFollowController) Store(w http.ResponseWriter, r *http.Request) {
	requestedUUID, err := uuid.Parse(chi.URLParam(r, "feedId"))
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	feed, err := cf.DBConnection.DB.GetFeedByID(r.Context(), requestedUUID)
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	err = cf.DBConnection.DB.CreateFeedFollow(r.Context(), db.CreateFeedFollowParams{
		UserID: authUser.ID,
		FeedID: feed.ID,
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Couldn't follow feed: %v", err))
		return
	}

	ut.RespondSuccessWithJSON(w, http.StatusCreated, "Successfully followed.")
}

func (c feedFollowController) Delete(w http.ResponseWriter, r *http.Request) {
	feedId, err := uuid.Parse(chi.URLParam(r, "feedId"))
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	// feed, err := cf.DBConnection.DB.GetFeedByID(r.Context(), requestedUUID)
	// if err != nil {
	// 	ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
	// 	return
	// }

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	err = cf.DBConnection.DB.DeleteFeedFollow(r.Context(), db.DeleteFeedFollowParams{
		FeedID: feedId,
		UserID: authUser.ID,
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Can not unfollow feed: %v", err))
		return
	}

	ut.RespondSuccessWithJSON(w, http.StatusCreated, "Successfully unfollowed.")
}

func (c feedFollowController) GetFeedFollowerCount(w http.ResponseWriter, r *http.Request) {
	requestedUUID, err := uuid.Parse(chi.URLParam(r, "feedId"))
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	feedFollowerCount, err := cf.DBConnection.DB.GetFeedFollowerCount(r.Context(), requestedUUID)
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	ut.RespondWithJSON(w, http.StatusOK, feedFollowerCount)
}
