package controllersapi

import (
	"fmt"
	"net/http"
	"strconv"

	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
	cf "github.com/naywin-programmer/RSS_Aggregator/configs"
	mi "github.com/naywin-programmer/RSS_Aggregator/middlewares"
	rs "github.com/naywin-programmer/RSS_Aggregator/resources"
	ut "github.com/naywin-programmer/RSS_Aggregator/utils"
)

type postController struct {
}

var PostController = postController{}

func (c postController) Index(w http.ResponseWriter, r *http.Request) {
	var limit int = 10

	page, err := strconv.Atoi(r.URL.Query().Get("page"))
	if err != nil {
		page = 1
	}

	offset := (page - 1) * limit
	if offset < 0 {
		offset = 0
	}

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	posts, err := cf.DBConnection.DB.GetPostsByUser(r.Context(), db.GetPostsByUserParams{
		UserID: authUser.ID,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Error while loading posts: %v", err))
		return
	}

	ut.RespondWithJSON(w, http.StatusOK, rs.ToPostResourceCollection(posts))
}
