package controllersapi

import (
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/httprate"
	"github.com/google/uuid"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
	cf "github.com/naywin-programmer/RSS_Aggregator/configs"
	mi "github.com/naywin-programmer/RSS_Aggregator/middlewares"
	rs "github.com/naywin-programmer/RSS_Aggregator/resources"
	ut "github.com/naywin-programmer/RSS_Aggregator/utils"
)

type userController struct {
	loginRateLimiter *httprate.RateLimiter
}

var UserController = userController{
	loginRateLimiter: httprate.NewRateLimiter(5, time.Minute),
}

func (c userController) SignUp(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Name string `json:"name"`
	}

	params, err := ut.DecodeJsonParams(w, r, &parameters{})
	if err != nil {
		return
	}

	user, err := cf.DBConnection.DB.SignUp(r.Context(), db.SignUpParams{
		ID:   uuid.New(),
		Name: params.Name,
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Couldn't create new user: %v", err))
		return
	}

	ut.RespondWithJSON(w, http.StatusCreated, rs.ToUserResource(user))
}

func (c userController) SignIn(w http.ResponseWriter, r *http.Request) {

	type parameters struct {
		Name string `json:"name"`
	}

	params, err := ut.DecodeJsonParams(w, r, &parameters{})
	if err != nil {
		return
	}

	// Rate-limit login at 5 req/min.
	if c.loginRateLimiter.RespondOnLimit(w, r, params.Name) {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Too many requests. Try again later.")
		return
	}

	user, err := cf.DBConnection.DB.SignIn(r.Context(), params.Name)
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Fail.")
		return
	}

	ut.RespondWithJSON(w, http.StatusOK, rs.ToUserResource(user))
}

func (c userController) GetUserCreatedFeeds(w http.ResponseWriter, r *http.Request) {
	var limit int = 10

	page, err := strconv.Atoi(r.URL.Query().Get("page"))
	if err != nil {
		page = 1
	}

	offset := (page - 1) * limit
	if offset < 0 {
		offset = 0
	}

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	feeds, err := cf.DBConnection.DB.GetAllFeedsByUserID(r.Context(), db.GetAllFeedsByUserIDParams{
		UserID: authUser.ID,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Error while loading feeds: %v", err))
		return
	}

	ut.RespondWithJSON(w, http.StatusOK, rs.ToFeedResourceCollection(feeds))
}

func (c userController) GetUserFollowedFeeds(w http.ResponseWriter, r *http.Request) {
	var limit int = 10

	page, err := strconv.Atoi(r.URL.Query().Get("page"))
	if err != nil {
		page = 1
	}

	offset := (page - 1) * limit
	if offset < 0 {
		offset = 0
	}

	authUser := mi.BasicApiAuthMiddleware.AuthUser
	if mi.BasicApiAuthMiddleware.Error != nil {
		ut.RespondErrorWithJSON(w, http.StatusForbidden, "Authentication Error!")
		return
	}

	followedFeeds, err := cf.DBConnection.DB.GetFollowedFeeds(r.Context(), db.GetFollowedFeedsParams{
		UserID: authUser.ID,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		ut.RespondErrorWithJSON(w, http.StatusBadRequest, fmt.Sprintf("Feed is not found: %v", err))
		return
	}

	feeds := make([]db.Feed, 0)
	for _, v := range followedFeeds {
		feedId, err := uuid.Parse(v.FeedID.String())
		if err != nil {
			continue
		}

		feed, err := cf.DBConnection.DB.GetFeedByID(r.Context(), feedId)
		if err != nil {
			continue
		}

		feeds = append(feeds, feed)
	}

	ut.RespondWithJSON(w, http.StatusOK, rs.ToFeedResourceCollection(feeds))
}
