package config

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/lib/pq"
	"github.com/naywin-programmer/RSS_Aggregator/autogenerated/database"
)

var DatabaseConnection DatabaseQueryApiConfig

type DatabaseQueryApiConfig struct {
	DB *database.Queries
}

func ConnectDatabase() {

	dbURL := os.Getenv("DB_URL")
	if dbURL == "" {
		log.Fatalln("DB_URL didn't found in the environment setting.")
	}

	connection, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatalln("Can't connect to database.")
	}

	pingErr := connection.Ping()
	if pingErr != nil {
		log.Fatalln(pingErr)
	}
	log.Println("Database Connected")

	DatabaseConnection = DatabaseQueryApiConfig{
		DB: database.New(connection),
	}
}
