package configs

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/lib/pq"
	db "github.com/naywin-programmer/RSS_Aggregator/autogenerated/autodatabase"
)

var DBConnection struct {
	DB *db.Queries
}

func ConnectDatabase() {

	dbURL := os.Getenv("DB_URL")
	if dbURL == "" {
		log.Fatalln("DB_URL didn't found in the environment setting.")
	}

	connection, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatalln("Can't connect to database.")
	}

	pingErr := connection.Ping()
	if pingErr != nil {
		log.Fatalln(pingErr)
	}

	DBConnection.DB = db.New(connection)
}
