package controller

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/naywin-programmer/RSS_Aggregator/auth"
	"github.com/naywin-programmer/RSS_Aggregator/autogenerated/database"
	"github.com/naywin-programmer/RSS_Aggregator/config"
	"github.com/naywin-programmer/RSS_Aggregator/resource"
	"github.com/naywin-programmer/RSS_Aggregator/utils"
)

func ResponseCreateUser(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Name string `json:"name"`
	}

	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		utils.RespondErrorWithJSON(w, 400, fmt.Sprintf("Request to JSON Parsing Error: %v", err))
		return
	}

	user, err := config.DatabaseConnection.DB.CreateUser(r.Context(), database.CreateUserParams{
		ID:   uuid.New(),
		Name: params.Name,
		// CreatedAt: time.Now().UTC(),
		// UpdatedAt: time.Now().UTC(),
	})
	if err != nil {
		utils.RespondErrorWithJSON(w, 400, fmt.Sprintf("Couldn't create new user: %v", err))
		return
	}

	utils.RespondWithJSON(w, 201, resource.ToUserResource(user))
}

func ResponseGetUserByApiKey(w http.ResponseWriter, r *http.Request) {
	apiKey, err := auth.GetApiKey(r.Header, auth.UserApiKeyPrefixInHeader)
	if err != nil {
		utils.RespondErrorWithJSON(w, 403, fmt.Sprintf("Authentication Error: %v", err))
		return
	}

	user, err := config.DatabaseConnection.DB.GetUserByApiKey(r.Context(), apiKey)
	if err != nil {
		utils.RespondErrorWithJSON(w, 400, fmt.Sprintf("User is not found: %v", err))
		return
	}

	utils.RespondWithJSON(w, 200, resource.ToUserResource(user))
}
